from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

APP_DIR = Path(__file__).resolve().parent.parent
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from dashboard_core import REPORTS_DIR, RESULTS_NOTEBOOK_DIR, page_support_rows, quantile_support_rows
from data_contracts.load_results import load_uncertainty_inputs

st.set_page_config(page_title="Data And Provenance", page_icon="C", layout="wide")

PROVENANCE_PATH = REPORTS_DIR / "PROVENANCE_REGISTRY_V2_1.csv"
SUPPORT_PATH = REPORTS_DIR / "DATA_SUPPORT_MATRIX_V2_1.csv"

st.title("Data And Provenance")
st.markdown(
    "This page records what is directly simulated, what is derived, what is assumed, and what stays conceptual in v3."
)
st.info(
    "Utility-only scope: the dashboard computes operational energy demand and emissions. Production, logistics, and end-of-life remain outside the quantitative support boundary."
)

download_col1, download_col2 = st.columns(2)
with download_col1:
    if PROVENANCE_PATH.exists():
        st.download_button(
            "Download Provenance Registry CSV",
            data=PROVENANCE_PATH.read_bytes(),
            file_name=PROVENANCE_PATH.name,
            mime="text/csv",
            width="stretch",
        )
with download_col2:
    if SUPPORT_PATH.exists():
        st.download_button(
            "Download Support Matrix CSV",
            data=SUPPORT_PATH.read_bytes(),
            file_name=SUPPORT_PATH.name,
            mime="text/csv",
            width="stretch",
        )

st.subheader("Tier Legend")
legend_df = pd.DataFrame(
    [
        {"Tier": "Direct simulation output", "Meaning": "Generated by `TransportModel` or aligned quantile summaries."},
        {"Tier": "Derived formula from simulation output", "Meaning": "Arithmetic on simulation outputs, such as cumulative emissions or turning year."},
        {"Tier": "Scenario assumption", "Meaning": "Config values, policy overrides, and future growth assumptions."},
        {"Tier": "Conceptual only / not quantitatively implemented", "Meaning": "Described for boundary clarity but not computed by the repo."},
    ]
)
st.dataframe(legend_df, width="stretch", hide_index=True)

st.subheader("Uncertainty Inputs Actually Sampled")
uncertainty_inputs = load_uncertainty_inputs()
if uncertainty_inputs is not None:
    st.dataframe(uncertainty_inputs, width="stretch", hide_index=True)
    st.caption(f"Loaded from `{RESULTS_NOTEBOOK_DIR / 'uncertainty_inputs_table.csv'}`.")
else:
    st.warning("`uncertainty_inputs_table.csv` is missing, so this table cannot be shown.")

st.subheader("Quantile File Support By Region And Policy")
support_df = pd.DataFrame(quantile_support_rows())
for column in ["config_defined", "runtime_deterministic", "deterministic_csv", "results_quantiles", "notebook_quantiles", "any_quantiles", "aligned_quantiles", "aligned_band_visible", "legacy_notebook_quantiles"]:
    support_df[column] = support_df[column].map(lambda value: "yes" if value else "no")
st.dataframe(support_df, width="stretch", hide_index=True)

st.subheader("Page-Level Support Matrix")
st.dataframe(pd.DataFrame(page_support_rows()), width="stretch", hide_index=True)

st.subheader("Provenance Registry")
if PROVENANCE_PATH.exists():
    provenance_df = pd.read_csv(PROVENANCE_PATH)
    st.dataframe(provenance_df, width="stretch", hide_index=True)
else:
    st.warning("`PROVENANCE_REGISTRY_V2_1.csv` has not been generated yet.")

st.subheader("Data Support Matrix")
if SUPPORT_PATH.exists():
    matrix_df = pd.read_csv(SUPPORT_PATH)
    st.dataframe(matrix_df, width="stretch", hide_index=True)
else:
    st.warning("`DATA_SUPPORT_MATRIX_V2_1.csv` has not been generated yet.")

st.caption("Styler-based coloring was removed on purpose so this page stays stable across pandas versions.")
