"""CLEAR-ATS v6 dashboard — landing page.

v6 inherits v5 page logic, palette, and calculations bit-exact. The only
additions are five reviewer-defensibility pages (03-07) that explain
uncertainty layering, benchmark-year marginals, dominant epistemic drivers,
and how to read long-horizon spread without over-claiming.
"""
from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="CLEAR-ATS v6",
    page_icon="C",
    layout="wide",
)

st.title("CLEAR-ATS: Clean Energy Automated Road Transport System")
st.caption(
    "Dashboard v6 (light-touch upgrade of v5). Scenario Explorer in four blocks. "
    "Utility-phase only. California and Ohio quantitative; U.S. Average quarantined."
)

st.markdown(
    """
This dashboard projects the **utility-phase** annual energy demand and
CO\u2082 emissions of Connected Autonomous Vehicles (CAV), Smart Traffic
Infrastructure (STI), and their integrated Automated Transport System (ATS)
for California and Ohio from 2024 onward.

### Pages

| Page | Purpose |
|------|---------|
| **Scenario Explorer** | Primary interactive page. Four blocks: mitigation and policy levers, fixed data, modeling assumptions, residual uncertainty priors. Three Nature-grade figures: ATS emissions band, top uncertainty drivers, layer contribution summary. |
| **One-Time Energy** | Production + logistics phase. Four-block layout. Component-level Figure A; unit-stacking Figure C. |
| **System Boundary** | Scope disclosure. Manufacturing, logistics, and end-of-life phases are declared out of scope. External life-cycle assessment literature is referenced for context. |
| **Uncertainty Definitions** *(v6 addition)* | Compact table mapping the existing L1 / L2 / L3 layers to epistemic vs aleatoric vocabulary, plus a per-layer interpretation block. Calculations unchanged. |
| **Uncertainty Architecture** *(v6 addition)* | Three-stage schematic adapted to CLEAR-ATS: deterministic baseline → within-scenario uncertainty → driver identification. Shows where L1/L2 sit and where L3 sits. |
| **Benchmark-Year Distributions** *(v6 addition)* | Distribution / violin views at 2035, 2045, 2055, 2075 derived from existing committed MC bundles. Avoids relying on a single long-horizon shaded band. |
| **Key Epistemic Drivers** *(v6 addition)* | Ranking view of top L3 / pathway drivers using the existing `PARAMETER_CONTRIBUTION_EXPERIMENT.csv`. Method labelled honestly. |
| **Mitigate Long-Horizon Uncertainty** *(v6 addition)* | Reviewer-defensibility page: how to read large L3 spread without claiming false predictability. Compares absolute vs relative band width. |

### v6 design in brief

- **Inherits v5 bit-exact.** v5 calculations, palette, page layout, cards, and core figures are preserved unchanged. The five new pages are additive only.
- **Uncertainty naming improved, not the math.** L1 / L2 / L3 layer objects keep their existing computation. The new pages provide an honest mapping to epistemic / aleatoric vocabulary inspired by recent literature (2025 *Nature Communications* energy-transition paper, Puerto Rico case).
- **No new dependencies.** Same `requirements.txt` as v5.
- **No port from the heavy-rearchitecture v6.** That earlier branch is preserved on disk as `v6_uncertainty_rearchitecture/` but is not imported here.

### Scientific boundary

Every quantitative line, band, and table refers to utility-phase energy
and emissions only. Production, logistics, and end-of-life phases are
discussed on the System Boundary page and are not computed. U.S. Average
is quarantined from paper-facing quantitative comparison.

### Reproducibility

The Monte Carlo bundles under `results/` are regenerated by
`scripts/regenerate_default_bundle_quantiles.py` using the same
`footprint_model.py` simulator that the live page calls. The committed
bundles ship with metadata sidecars for seed, sample count, and
prior-specification hash. v6 reads these bundles unchanged.
"""
)

st.caption(
    "See `reports/V6_RECONSTRUCTED_FROM_V5.md` for the migration note and "
    "`reports/UNCERTAINTY_NAMING_AND_INTERPRETATION_V6.md` for the layer-name mapping. "
    "v5 sign-off: `audits/final_consistency/FINAL_VALIDATION_AND_POLISH_STATUS.md`."
)
