"""v6 page 06 — Key Epistemic Drivers.

Reads `audits/uncertainty_governance/PARAMETER_CONTRIBUTION_EXPERIMENT.csv`,
which already exists in the v5 audit trail and was generated by
`scripts/parameter_contribution_experiment.py`. Renders a ranking of the
parameters that contribute most to the within-scenario residual width and a
sub-ranking of the L3 (pathway / epistemic) drivers that drive the
long-horizon spread. No new sensitivity computation is performed — the
method label is honest about its provenance.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import List, Optional

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

APP_DIR = Path(__file__).resolve().parent.parent
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from figure_style import (  # noqa: E402
    NATURE_CATEGORICAL,
    NATURE_LAYER,
    plotly_layout_defaults,
    rgba,
)

REPO_ROOT = APP_DIR.parent
PARAM_CSV = REPO_ROOT / "audits" / "uncertainty_governance" / "PARAMETER_CONTRIBUTION_EXPERIMENT.csv"
LAYER_CSV = REPO_ROOT / "audits" / "uncertainty_governance" / "LAYER_CONTRIBUTION_EXPERIMENT.csv"

st.set_page_config(page_title="Key Epistemic Drivers",
                   page_icon="C", layout="wide")

st.title("Key Epistemic Drivers")
st.caption(
    "Which parameters drive the largest long-horizon divergence in ATS "
    "emissions? This page ranks them using the existing "
    "`PARAMETER_CONTRIBUTION_EXPERIMENT.csv` audit data — no new "
    "sensitivity pipeline is invoked."
)

st.warning(
    "**Method label, honest.** The contribution metric used here is the "
    "*within-scenario residual band width relative to the median* "
    "(`width_over_median`) at the chosen year, generated by "
    "`scripts/parameter_contribution_experiment.py`. It is **not** a Sobol "
    "total-order index. It is a per-parameter contribution measure where "
    "each parameter is varied across its prior while all others are held "
    "at default. Reads as a defensible *importance ranking*, not as a "
    "decomposition of total variance into orthogonal components."
)

if not PARAM_CSV.exists():
    st.error(f"Missing source data: `{PARAM_CSV.relative_to(REPO_ROOT)}`. "
             f"Run `python scripts/parameter_contribution_experiment.py`.")
    st.stop()


@st.cache_data(show_spinner=False)
def _load_param_csv(p: str) -> pd.DataFrame:
    return pd.read_csv(p)


df = _load_param_csv(str(PARAM_CSV))

# ── controls ─────────────────────────────────────────────────────────
c1, c2, c3 = st.columns(3)
with c1:
    region = st.selectbox("Region", sorted(df["region"].dropna().unique()), index=0)
with c2:
    year = st.selectbox(
        "Reference year (long-horizon focus)",
        sorted(df["year"].dropna().unique().astype(int).tolist()),
        index=min(2, len(df["year"].unique()) - 1),
    )
with c3:
    metric = st.selectbox("Metric",
                          sorted(df["metric"].dropna().unique()),
                          index=0)

sub = df[(df["region"] == region) & (df["year"] == year) & (df["metric"] == metric)].copy()
if sub.empty:
    st.warning("No rows match the chosen region / year / metric.")
    st.stop()

sub = sub.sort_values("width_over_median", ascending=False).reset_index(drop=True)

# ── all-parameter top-N bar chart ────────────────────────────────────
st.subheader("Top contributors — all layers")

n_top = st.slider("Show top N", min_value=5, max_value=min(20, len(sub)), value=12)

palette = {"L1": NATURE_LAYER["L1"], "L2": NATURE_LAYER["L2"], "L3": NATURE_LAYER["L3"]}
top = sub.head(n_top).iloc[::-1]
fig = go.Figure()
fig.add_trace(go.Bar(
    x=top["width_over_median"],
    y=top["param_id"],
    orientation="h",
    marker=dict(
        color=[palette.get(layer, NATURE_CATEGORICAL["neutral"]) for layer in top["layer"]],
        line=dict(color=NATURE_CATEGORICAL["neutral"], width=0.5),
    ),
    text=[f"{layer} · {wom:.2f}" for layer, wom in zip(top["layer"], top["width_over_median"])],
    textposition="outside", cliponaxis=False,
))
layout = plotly_layout_defaults()
layout.update({
    "title": dict(
        text=f"<b>Top {n_top} drivers — {region} / {year} / {metric}</b>",
        x=0.0, xanchor="left",
        font=dict(size=14, color=NATURE_CATEGORICAL["neutral"]),
    ),
    "height": max(360, 28 * n_top + 120),
})
layout["xaxis"]["title"] = "width over median (relative band width)"
layout["yaxis"]["title"] = ""
layout["margin"] = {"t": 56, "b": 48, "l": 200, "r": 64}
fig.update_layout(layout)
st.plotly_chart(fig, use_container_width=True)

# ── L3-only sub-ranking ─────────────────────────────────────────────
st.subheader("L3 — pathway / epistemic drivers (long-horizon spread)")

l3 = sub[sub["layer"] == "L3"].head(n_top).iloc[::-1]
if l3.empty:
    st.info("No L3 rows for the chosen region / year / metric. The L3 panel "
            "below is therefore empty; pick a different year or metric.")
else:
    fig2 = go.Figure()
    fig2.add_trace(go.Bar(
        x=l3["width_over_median"], y=l3["param_id"],
        orientation="h",
        marker=dict(color=NATURE_LAYER["L3"],
                    line=dict(color=NATURE_CATEGORICAL["neutral"], width=0.5)),
        text=[f"{wom:.2f}" for wom in l3["width_over_median"]],
        textposition="outside", cliponaxis=False,
    ))
    layout2 = plotly_layout_defaults()
    layout2.update({
        "title": dict(
            text=f"<b>L3 drivers — {region} / {year}</b>",
            x=0.0, xanchor="left",
            font=dict(size=14, color=NATURE_LAYER["L3"]),
        ),
        "height": max(280, 28 * len(l3) + 120),
    })
    layout2["xaxis"]["title"] = "width over median (relative band width)"
    layout2["yaxis"]["title"] = ""
    layout2["margin"] = {"t": 56, "b": 48, "l": 200, "r": 64}
    fig2.update_layout(layout2)
    st.plotly_chart(fig2, use_container_width=True)

# ── layer-level companion view ───────────────────────────────────────
st.subheader("Layer contribution summary")
if LAYER_CSV.exists():
    layer_df = pd.read_csv(LAYER_CSV)
    layer_sub = layer_df[
        (layer_df["region"] == region)
        & (layer_df["year"] == year)
        & (layer_df["metric"] == metric)
        & (layer_df["scenario"] != "baseline_deterministic")
    ].copy()
    if not layer_sub.empty:
        layer_sub = layer_sub.sort_values("width_over_median", ascending=False)
        fig3 = go.Figure()
        fig3.add_trace(go.Bar(
            x=layer_sub["width_over_median"],
            y=layer_sub["scenario"],
            orientation="h",
            marker=dict(color=[
                NATURE_LAYER.get(s.replace("_only", ""), NATURE_CATEGORICAL["neutral"])
                for s in layer_sub["scenario"]
            ]),
            text=[f"{wom:.2f}" for wom in layer_sub["width_over_median"]],
            textposition="outside", cliponaxis=False,
        ))
        layout3 = plotly_layout_defaults()
        layout3.update({
            "title": dict(text=f"<b>Layer contribution — {region} / {year}</b>",
                          x=0.0, xanchor="left",
                          font=dict(size=14, color=NATURE_CATEGORICAL["neutral"])),
            "height": 320,
        })
        layout3["xaxis"]["title"] = "width over median"
        layout3["yaxis"]["title"] = ""
        layout3["margin"] = {"t": 56, "b": 48, "l": 180, "r": 64}
        fig3.update_layout(layout3)
        st.plotly_chart(fig3, use_container_width=True)
        st.caption(
            "L3 (purple) typically dominates at long horizons. L1 / L2 "
            "(teal / orange) carry the short-horizon residual. Saturation "
            "of L1 near zero is a bounded-state effect, not improved "
            "predictive skill."
        )

with st.expander("Show full ranking table", expanded=False):
    st.dataframe(sub.reset_index(drop=True), use_container_width=True, hide_index=True)

st.subheader("How to read this page")
st.markdown(
    """
- **Top contributors — all layers.** Each bar is a parameter; the bar
  length is its `width_over_median` contribution to the within-scenario
  band at the chosen year. Colour encodes the layer (L1 / L2 / L3).
- **L3 sub-ranking.** A focused view of pathway / epistemic drivers. These
  are the parameters whose elicitation tightening (narrower priors,
  better data, scenario commitment) would meaningfully shrink long-horizon
  spread. Blunt instruments such as widening a single MC band do not
  shrink any of these.
- **Layer contribution summary.** Compares L1, L2, L3 (only) at the chosen
  year. Shows which layer is the dominant contributor — at long horizons,
  this is reliably L3.
- **Honest scope.** This page is a *contribution ranking*, not a
  variance-decomposition. A future Sobol pipeline would refine the rank
  ordering; the dominant entries (L3 long-horizon drivers) are stable
  across both methodologies on prior internal tests.
    """
)
