"""CLEAR-ATS v5 dashboard — landing page."""
from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="CLEAR-ATS v5",
    page_icon="C",
    layout="wide",
)

st.title("CLEAR-ATS: Clean Energy Automated Road Transport System")
st.caption(
    "Dashboard v5. Scenario Explorer in four blocks. Utility-phase only. "
    "California and Ohio quantitative; U.S. Average quarantined."
)

st.markdown(
    """
This dashboard projects the **utility-phase** annual energy demand and
CO\u2082 emissions of Connected Autonomous Vehicles (CAV), Smart Traffic
Infrastructure (STI), and their integrated Automated Transport System (ATS)
for California and Ohio from 2024 onward.

### Pages

| Page | Purpose |
|------|---------|
| **Scenario Explorer** | Primary interactive page. Four blocks: mitigation and policy levers, fixed data, modeling assumptions, residual uncertainty priors. Three Nature-grade figures: ATS emissions band, top uncertainty drivers, layer contribution summary. |
| **System Boundary** | Scope disclosure. Manufacturing, logistics, and end-of-life phases are declared out of scope. External life-cycle assessment literature is referenced for context. |

### v5 design in brief

- Four-block restructure preserved exactly from v4.
- Nature-family figure style applied consistently across every chart.
- Fix wired for the previous silent fallback that showed California
  parameter drivers when a reader selected Ohio.
- Matching static exports live under `figures/` for paste into the manuscript.
- Mitigation defaults, parameter registry, and bundle files are shared with
  v3 and v4; no duplication of simulation artifacts.

### Scientific boundary

Every quantitative line, band, and table refers to utility-phase energy
and emissions only. Production, logistics, and end-of-life phases are
discussed on the System Boundary page and are not computed. U.S. Average
is quarantined from paper-facing quantitative comparison.

### Reproducibility

The Monte Carlo bundles under `results/` are regenerated by
`scripts/regenerate_default_bundle_quantiles.py` using the same
`footprint_model.py` simulator that the live page calls. The committed
bundles ship with metadata sidecars for seed, sample count, and
prior-specification hash.
"""
)

st.caption(
    "See audits/final_consistency/FINAL_VALIDATION_AND_POLISH_STATUS.md "
    "for the v5 validation and polish sign-off."
)
