"""CLEAR-ATS v6 dashboard — landing page."""
from __future__ import annotations

import streamlit as st

st.set_page_config(
    page_title="CLEAR-ATS v6",
    page_icon="C",
    layout="wide",
)

st.title("CLEAR-ATS: Clean Energy Automated Road Transport System")
st.caption(
    "Dashboard v6. Scenario Explorer in four blocks. Utility-phase only. "
    "California and Ohio quantitative; U.S. Average quarantined. Single-layer "
    "state-conditioned weather-share modifier on utility energy and grid CO₂."
)

st.markdown(
    """
This dashboard projects the **utility-phase** annual energy demand and
CO₂ emissions of Connected Autonomous Vehicles (CAV), Smart Traffic
Infrastructure (STI), and their integrated Automated Transport System (ATS)
for California and Ohio from 2024 onward.

### Pages

| Page | Purpose |
|------|---------|
| **Scenario Explorer** | Primary interactive page. Four blocks: mitigation and policy levers, fixed data, modeling assumptions, residual uncertainty priors. v6 adds a compact weather-module section in the sidebar. |
| **One-Time Energy** | Production + logistics phase. Weather module does NOT apply here; this page is unchanged from v5. |
| **System Boundary** | Scope disclosure. Manufacturing, logistics, and end-of-life phases are declared out of scope. |

### What is new in v6

v6 replaces the previous two-object / multi-layer weather uncertainty
treatment with a **single annual weather-distribution modifier** applied
directly inside the utility-phase energy and CO₂ calculation.

- Three mutually exclusive weather classes: clear, cloudy, adverse.
- State-specific monthly climatology for California and Ohio.
- Single annual draw mechanism (a Dirichlet centred on each month's
  climatology, aggregated into one annual weather-share vector).
- The annual share reweights ECAV, ICECAV, and STI subsystem energy via
  manuscript-derived weather multipliers, and drives a state-specific
  grid-intensity multiplier on the electricity-side CO₂ term.
- There is no second uncertainty object, no outer-plus-inner loop, and
  no new uncertainty band taxonomy in the UI.
- Weather off reproduces v5 outputs to floating-point tolerance.

### v6 design principles (brief)

- No nested Monte Carlo for weather.
- No "epistemic vs aleatoric" split for weather; only one stochastic
  weather object per (state, year).
- Weather affects utility-phase energy and utility-phase grid CO₂ only.
  Production, logistics, and end-of-life are unaffected.
- Page order, figure palette, and block structure are preserved from v5.

### Scientific boundary

Every quantitative line, band, and table refers to utility-phase energy
and emissions only. Production, logistics, and end-of-life phases are
discussed on the System Boundary page and are not computed. U.S. Average
is quarantined from paper-facing quantitative comparison.

### Reproducibility

The Monte Carlo bundles under `results/` are regenerated by
`scripts/regenerate_default_bundle_quantiles.py` using the same
`footprint_model.py` simulator that the live page calls. The committed
bundles ship with metadata sidecars for seed, sample count, and
prior-specification hash. Weather module priors and multipliers live
under `configs/weather_singlelayer/`.
"""
)

st.caption(
    "Validation: scripts/validate_v6_weather.py checks weather-share "
    "normalisation, weather-off equivalence with v5, adverse-share "
    "monotonicity for sensing and computing, and CA / OH CO₂ response "
    "divergence driven by grid intensity."
)
